### ISSUE TITLE
Testing Geogrid for my case: Facing some errors

### ISSUE THREAD

**Issue by Sci123-lab** [leiyangleon/Geogrid#10]
Hi there,

I have installed ISCE2 and have autorift and geogrid all set.  I have done initial processing to co-register Sentinel-1 pair (used 2 sub-swaths). Also, I have transformed DEM to the required format of the geogrid. The code I run for geogrid is as follows:

**testGeogrid_ISCE.py -m /home/hassan/ISCE2-Tops/insar/merged/reference_grd.tif  -s /home/hassan/ISCE2-Tops/insar/merged/secondary_grd.tif -d /home/hassan/ISCE2-Tops/insar/merged/dem_nztm.tif**

based on instructions, I see that  we should set -m -s as folders to co-registered SLC's. I am wondering what could be the problem. The folder "merged" contains all the files required for this step, i.e., reference and secondary slc's and their metadata.

The error i get is as follows:

Traceback (most recent call last):
  File "/home/hassan/miniconda3/envs/isce2/lib/python3.8/site-packages/isce/applications/testGeogrid_ISCE.py", line 392, in <module>
    main()
  File "/home/hassan/miniconda3/envs/isce2/lib/python3.8/site-packages/isce/applications/testGeogrid_ISCE.py", line 386, in main
    metadata_m = loadMetadata(inps.indir_m)
  File "/home/hassan/miniconda3/envs/isce2/lib/python3.8/site-packages/isce/applications/testGeogrid_ISCE.py", line 131, in loadMetadata
    info.sensingStart = min([x.sensingStart for x in frames])
ValueError: min() arg is an empty sequence

Any advice?

**Comment by walking02** [comment]
I have the same problem, ask for help

**Comment by barely-sad-one** [comment]
Is it resolved? I'm also having this same error.

**Comment by walking02** [comment]
I'm sorry, I haven't found a solution either.
&nbsp;


如初
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ": ***@***.***&gt;; 
发送时间: 2025年4月6日(星期天) 凌晨2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leiyangleon/Geogrid] Testing Geogrid for my case: Facing some errors (Issue #10)












   
Is it resolved? I'm also having this same error.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  barely-sad-one left a comment (leiyangleon/Geogrid#10)
 
Is it resolved? I'm also having this same error.

**Comment by Sci123-lab** [comment]
Hi.
I am also waiting to hear. Lets wait to hear from an expert

**Comment by barely-sad-one** [comment]
RESOLVED this perticular issue.


testGeogrid.py is trying to find some metadata in the Sentinel-2 raster's description metadata, but the raster I downloaded doesn’t include this information, which is causing the error. 
It might be necessary to hardcode the time value, but I’m not entirely sure.

**Comment by Sci123-lab** [comment]
> RESOLVED this perticular issue.
> 
> testGeogrid.py is trying to find some metadata in the Sentinel-2 raster's description metadata, but the raster I downloaded doesn’t include this information, which is causing the error. It might be necessary to hardcode the time value, but I’m not entirely sure.

OKAY. Well I am dealing with Sentinel-1 radar images and they do have their metadata always included in the .SAFE. Still Wondering

**Comment by CherishGY** [comment]
I am processing Sentinel-1 data using ISCE2 and AutoRIFT to calculate ice velocity, but I’m currently stuck on how to obtain the corresponding master.tif and slave.tif files. As in your example /home/hassan/ISCE2-Tops/insar/merged/reference_grd.tif, after running topsApp.py /mnt/h/Velocity/topsApp.xml --start=startup --end=denseoffsets, I only get files like reference.slc.full, reference.slc.full.aux.xml, reference.slc.full.vrt, reference.slc.full.xml, etc. According to some papers, processing only up to mergebursts is sufficient, in which case even the reference.slc.full file does not appear. I want to know how to generate master.tif, because in the latest version of AutoRIFT, testGeogrid.py requires two geocoded .tif files. I'm not sure how to handle this. Do you have any suggestions?

**Comment by Sci123-lab** [comment]
@CherishGY you are right. We don't get these files directly and one can convert to tif always, but it also doesn't solve the problem. It's more complicated than that.
I just used denseAmpcor to get my dense offsets. But I am still wondering to know the usability of autoRIFT for offset calculations using SAR images
